/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as BuyCryptoRouteImport } from './routes/buy-crypto'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as HelpTermsRouteImport } from './routes/help.terms'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicNowpaymentsWebhookRouteImport } from './routes/api/public/nowpayments-webhook'
import { Route as AuthenticatedAccountVerificationRouteImport } from './routes/_authenticated/account.verification'
import { Route as AuthenticatedAccountSessionsRouteImport } from './routes/_authenticated/account.sessions'
import { Route as AuthenticatedAccountReferralsRouteImport } from './routes/_authenticated/account.referrals'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedAccountPasswordRouteImport } from './routes/_authenticated/account.password'
import { Route as AuthenticatedAccountActivitiesRouteImport } from './routes/_authenticated/account.activities'
import { Route as AuthenticatedAccount2faRouteImport } from './routes/_authenticated/account.2fa'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsFlutterwaveWebhookRouteImport } from './routes/api/public/payments/flutterwave-webhook'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCryptoRoute = BuyCryptoRouteImport.update({
  id: '/buy-crypto',
  path: '/buy-crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTermsRoute = HelpTermsRouteImport.update({
  id: '/help/terms',
  path: '/help/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicNowpaymentsWebhookRoute =
  ApiPublicNowpaymentsWebhookRouteImport.update({
    id: '/api/public/nowpayments-webhook',
    path: '/api/public/nowpayments-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountVerificationRoute =
  AuthenticatedAccountVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountSessionsRoute =
  AuthenticatedAccountSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountReferralsRoute =
  AuthenticatedAccountReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountPasswordRoute =
  AuthenticatedAccountPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountActivitiesRoute =
  AuthenticatedAccountActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccount2faRoute = AuthenticatedAccount2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AuthenticatedAccountRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsFlutterwaveWebhookRoute =
  ApiPublicPaymentsFlutterwaveWebhookRouteImport.update({
    id: '/api/public/payments/flutterwave-webhook',
    path: '/api/public/payments/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/affiliate': typeof AffiliateRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/exchange': typeof ExchangeRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/prices': typeof PricesRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/wallets': typeof AuthenticatedWalletsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/help/terms': typeof HelpTermsRoute
  '/blog/': typeof BlogIndexRoute
  '/account/2fa': typeof AuthenticatedAccount2faRoute
  '/account/activities': typeof AuthenticatedAccountActivitiesRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/referrals': typeof AuthenticatedAccountReferralsRoute
  '/account/sessions': typeof AuthenticatedAccountSessionsRoute
  '/account/verification': typeof AuthenticatedAccountVerificationRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/payments/flutterwave-webhook': typeof ApiPublicPaymentsFlutterwaveWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/affiliate': typeof AffiliateRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/exchange': typeof ExchangeRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/prices': typeof PricesRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/wallets': typeof AuthenticatedWalletsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/help/terms': typeof HelpTermsRoute
  '/blog': typeof BlogIndexRoute
  '/account/2fa': typeof AuthenticatedAccount2faRoute
  '/account/activities': typeof AuthenticatedAccountActivitiesRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/referrals': typeof AuthenticatedAccountReferralsRoute
  '/account/sessions': typeof AuthenticatedAccountSessionsRoute
  '/account/verification': typeof AuthenticatedAccountVerificationRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/payments/flutterwave-webhook': typeof ApiPublicPaymentsFlutterwaveWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/affiliate': typeof AffiliateRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/exchange': typeof ExchangeRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/prices': typeof PricesRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/help/terms': typeof HelpTermsRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/account/2fa': typeof AuthenticatedAccount2faRoute
  '/_authenticated/account/activities': typeof AuthenticatedAccountActivitiesRoute
  '/_authenticated/account/password': typeof AuthenticatedAccountPasswordRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/referrals': typeof AuthenticatedAccountReferralsRoute
  '/_authenticated/account/sessions': typeof AuthenticatedAccountSessionsRoute
  '/_authenticated/account/verification': typeof AuthenticatedAccountVerificationRoute
  '/api/public/nowpayments-webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/payments/flutterwave-webhook': typeof ApiPublicPaymentsFlutterwaveWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/affiliate'
    | '/buy-crypto'
    | '/exchange'
    | '/fees'
    | '/forgot-password'
    | '/login'
    | '/prices'
    | '/referral'
    | '/register'
    | '/vip'
    | '/account'
    | '/wallets'
    | '/blog/$slug'
    | '/help/terms'
    | '/blog/'
    | '/account/2fa'
    | '/account/activities'
    | '/account/password'
    | '/account/profile'
    | '/account/referrals'
    | '/account/sessions'
    | '/account/verification'
    | '/api/public/nowpayments-webhook'
    | '/api/public/payments/flutterwave-webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/affiliate'
    | '/buy-crypto'
    | '/exchange'
    | '/fees'
    | '/forgot-password'
    | '/login'
    | '/prices'
    | '/referral'
    | '/register'
    | '/vip'
    | '/account'
    | '/wallets'
    | '/blog/$slug'
    | '/help/terms'
    | '/blog'
    | '/account/2fa'
    | '/account/activities'
    | '/account/password'
    | '/account/profile'
    | '/account/referrals'
    | '/account/sessions'
    | '/account/verification'
    | '/api/public/nowpayments-webhook'
    | '/api/public/payments/flutterwave-webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-us'
    | '/affiliate'
    | '/buy-crypto'
    | '/exchange'
    | '/fees'
    | '/forgot-password'
    | '/login'
    | '/prices'
    | '/referral'
    | '/register'
    | '/vip'
    | '/_authenticated/account'
    | '/_authenticated/wallets'
    | '/blog/$slug'
    | '/help/terms'
    | '/blog/'
    | '/_authenticated/account/2fa'
    | '/_authenticated/account/activities'
    | '/_authenticated/account/password'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/referrals'
    | '/_authenticated/account/sessions'
    | '/_authenticated/account/verification'
    | '/api/public/nowpayments-webhook'
    | '/api/public/payments/flutterwave-webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  AffiliateRoute: typeof AffiliateRoute
  BuyCryptoRoute: typeof BuyCryptoRoute
  ExchangeRoute: typeof ExchangeRoute
  FeesRoute: typeof FeesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricesRoute: typeof PricesRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  VipRoute: typeof VipRoute
  BlogSlugRoute: typeof BlogSlugRoute
  HelpTermsRoute: typeof HelpTermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicNowpaymentsWebhookRoute: typeof ApiPublicNowpaymentsWebhookRoute
  ApiPublicPaymentsFlutterwaveWebhookRoute: typeof ApiPublicPaymentsFlutterwaveWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-crypto': {
      id: '/buy-crypto'
      path: '/buy-crypto'
      fullPath: '/buy-crypto'
      preLoaderRoute: typeof BuyCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/terms': {
      id: '/help/terms'
      path: '/help/terms'
      fullPath: '/help/terms'
      preLoaderRoute: typeof HelpTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/nowpayments-webhook': {
      id: '/api/public/nowpayments-webhook'
      path: '/api/public/nowpayments-webhook'
      fullPath: '/api/public/nowpayments-webhook'
      preLoaderRoute: typeof ApiPublicNowpaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/verification': {
      id: '/_authenticated/account/verification'
      path: '/verification'
      fullPath: '/account/verification'
      preLoaderRoute: typeof AuthenticatedAccountVerificationRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/sessions': {
      id: '/_authenticated/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof AuthenticatedAccountSessionsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/referrals': {
      id: '/_authenticated/account/referrals'
      path: '/referrals'
      fullPath: '/account/referrals'
      preLoaderRoute: typeof AuthenticatedAccountReferralsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/password': {
      id: '/_authenticated/account/password'
      path: '/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthenticatedAccountPasswordRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/activities': {
      id: '/_authenticated/account/activities'
      path: '/activities'
      fullPath: '/account/activities'
      preLoaderRoute: typeof AuthenticatedAccountActivitiesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/2fa': {
      id: '/_authenticated/account/2fa'
      path: '/2fa'
      fullPath: '/account/2fa'
      preLoaderRoute: typeof AuthenticatedAccount2faRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/flutterwave-webhook': {
      id: '/api/public/payments/flutterwave-webhook'
      path: '/api/public/payments/flutterwave-webhook'
      fullPath: '/api/public/payments/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccount2faRoute: typeof AuthenticatedAccount2faRoute
  AuthenticatedAccountActivitiesRoute: typeof AuthenticatedAccountActivitiesRoute
  AuthenticatedAccountPasswordRoute: typeof AuthenticatedAccountPasswordRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountReferralsRoute: typeof AuthenticatedAccountReferralsRoute
  AuthenticatedAccountSessionsRoute: typeof AuthenticatedAccountSessionsRoute
  AuthenticatedAccountVerificationRoute: typeof AuthenticatedAccountVerificationRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccount2faRoute: AuthenticatedAccount2faRoute,
  AuthenticatedAccountActivitiesRoute: AuthenticatedAccountActivitiesRoute,
  AuthenticatedAccountPasswordRoute: AuthenticatedAccountPasswordRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountReferralsRoute: AuthenticatedAccountReferralsRoute,
  AuthenticatedAccountSessionsRoute: AuthenticatedAccountSessionsRoute,
  AuthenticatedAccountVerificationRoute: AuthenticatedAccountVerificationRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  AffiliateRoute: AffiliateRoute,
  BuyCryptoRoute: BuyCryptoRoute,
  ExchangeRoute: ExchangeRoute,
  FeesRoute: FeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricesRoute: PricesRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  VipRoute: VipRoute,
  BlogSlugRoute: BlogSlugRoute,
  HelpTermsRoute: HelpTermsRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicNowpaymentsWebhookRoute: ApiPublicNowpaymentsWebhookRoute,
  ApiPublicPaymentsFlutterwaveWebhookRoute:
    ApiPublicPaymentsFlutterwaveWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
